[30기 김광일] 소셜로그인 기능 구현
wecode-bootcamp-korea/30-2nd-README-backend pull request #4
Opened 2022-03-18 04:11 UTC by Kimgwangil

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 소셜로그인 기능 구현 및 테스트 코드 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 소셜 로그인

2. 유저 정보가 없을 시 로그인 후 닉네임과 생년월일 정보 따로 수집

3. 로그인 데코레이터

4. 테스트 코드

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 소셜로그인의 로직에 대해 이해를 하였습니다.
- 테스트 코드에 대해 공부를 하였습니다.
- 로그인 데코레이터가 있는 함수의 테스트 코드 작성 시 `headers = {'HTTP_Authorization' : 'access_token'}`

<br />

## :: 기타 질문 및 특이 사항

2022-03-18 08:18 UTC, jamessoun93 requested changes

2022-03-18 08:18 UTC, jamessoun93 commented on users/urls.py
> +    path('/signin/update', UserUpdateView.as_view())
`/users/signin/update` 가 아닌 /users` 에 PUT 혹은 PATCH로 처리하면 되겠네요.

2022-03-18 08:18 UTC, jamessoun93 commented on users/views.py
> +            user_inforamtion_api = 'https://kapi.kakao.com/v2/user/me'
api 주소같은 값은 상수로 선언해주세요. 
파이썬 자체에서 상수를 서포트하진 않지만 상수의 의미로 사용하기 위해 변수명을 대문자로 지어주시면 됩니다.

```python
API_URL = 'https://...'
```

2022-03-18 08:18 UTC, jamessoun93 commented on users/views.py
> +            point                = 500000
이런 부분도 상수의 의미로 사용해주셔야겠죠?

2022-03-18 08:18 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'access_token' : access_token}, status = status)
exception 처리 꼭 해주셔야합니다.

2022-03-18 08:18 UTC, jamessoun93 commented on users/views.py
> +            )
- 데코레이터를 통해 user 객체를 넘겨받게되는데 굳이 여기서 user.id로 또 찾을 필요가 없습니다.
- 그리고 만약 user 객체를 넘겨받지 않았다고 해도 단일 객체에 대한 정보를 업데이트하기 위함이니 더 명확하게 객체 하나만 가지고 와서 update 해주시는게 좋습니다. 해당 조건에 맞는 user 객체가 존재하지 않을수도 있으니까요.

```python
user.date_of_birth = date_of_birth
user.nickname      = nickname
user.save()
```

2022-03-18 10:29 UTC, Kimgwangil commented on users/urls.py
> +    path('/signin/update', UserUpdateView.as_view())
일부 내용만 바뀌는 상황이라 `PATCH` 사용하였습니다!

2022-03-18 10:47 UTC, Kimgwangil commented on users/views.py
> +            user_inforamtion_api = 'https://kapi.kakao.com/v2/user/me'
넵 ! 적용했습니다!

2022-03-18 10:48 UTC, Kimgwangil commented on users/views.py
> +            return JsonResponse({'access_token' : access_token}, status = status)
헤더에 카카오 인가 토큰이 빠진 경우 15번 라인에서 키에러가 발생하는 것을 확인하고 키에러 처리를 하였습니다. 혹시 다른 에러가 생길만한 부분이 있을까요?

2022-03-18 10:49 UTC, Kimgwangil commented on users/views.py
> +            )
혹시 이 부분은 `User.objects.filter(user = user).update(...` 이렇게 사용해도 무관한 걸까요?

2022-03-19 07:40 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'access_token' : access_token}, status = status)
requests에 timeout 옵션 추가해주세요. 어떤 의미인지는 직접 알아보시고 적절한 시간 정해서 추가해주세요!

2022-03-19 07:41 UTC, jamessoun93 commented on users/views.py
> +            )
filter를 통한 업데이트를 사용하고 싶으신 이유가 있으신가요?

2022-03-19 08:39 UTC, Kimgwangil commented on users/views.py
> +            return JsonResponse({'access_token' : access_token}, status = status)
헤더에 담길 정보를 requests 를 사용하여 받아오는데, 이 때 요청이 지연되는 경우 timeout 을 설정하지 않으면 한없이 대기하는 상황이 생깁니다. 이런 상황을 방지하기 위해 timeout 시간을 설정해주고, 요청시간초과를 의미하는 408을 반환해줍니다. 현재는 넉넉하게 5초면 넉넉할 것이라 판단되었습니다.  에러를 확인하기 위하여 시간을 줄여가는데 0.02로 설정했을 때 에러가 발생했습니다.

2022-03-19 08:43 UTC, Kimgwangil commented on users/views.py
> +            return JsonResponse({'access_token' : access_token}, status = status)
여기서 궁금한 사항이 에러가 반환되면 프론트 측에서 다시 로딩을 하도록 처리하는 것이 효율적인가요..?
 백엔드에서 다시 실행을 시키는 로직을 짜놓는 것이 효율적인가요..??

2022-03-19 08:46 UTC, Kimgwangil commented on users/views.py
> +            )
동기들과 정보를 공유하던 중 filter를 통한 업데이트의 속도가 더 빠르지 않냐는 얘기가 나왔습니다.
검색해보니 save보다 filter가 더  빠르다는 결론이 서게 되어서 여쭤봤습니다!

2022-03-19 14:38 UTC, jamessoun93 commented on users/views.py
> +            )
넵 검색 잘 해보셨는데 구체적으로 어떤 차이로 인해 filter가 더 빠르다고 하는지 이해는 되셨나요?

2022-03-19 14:38 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'access_token' : access_token}, status = status)
다시 요청하게끔 해주세요!

2022-03-20 13:51 UTC, Kimgwangil commented on users/views.py
> +            return JsonResponse({'access_token' : access_token}, status = status)
간단하리라 생각했지만, session 과 mount를 이용해 다시 요청하는 로직을 찾아봤는데 이해가 쉽지 않습니다..ㅠㅠ 카트랑 오더 기능 구현에 뭔가 쫓기기도 하고.. 혹시 다시 요청하는 부분은 추가로 구현해도 괜찮을까요..?

2022-03-20 13:59 UTC, Kimgwangil commented on users/views.py
> +            )
filter를 사용한 업데이트는 db에 바로 적용이 되고, save는  따로 호출해주기 전까지 db에 도달하지 않는다.. 라고 공식문서에서 봤습니다.. 또 다른 블로그 글에서는 하나의 모델 객체를 바탕으로 DB에 새로 생성하거나 업데이트할 때는 save를 사용하고, 특정 필드만 업데이트 하는 경우에는 filter를 통한 update를 사용하는 것이 좋다고 했는데, 같은 말 같으면서도 다른 말 같아 이해가 잘 안 됩니다..
그럼 후에 수정이나, 해당 항목을 재사용할 시 save 가 좀 더 유리한 걸까요..?

2022-03-21 05:42 UTC, merged