[30기 임정찬] Create: main page filtering
wecode-bootcamp-korea/30-2nd-README-backend pull request #5
Opened 2022-03-18 04:18 UTC by L-jungchan

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 리디북스 메인페이지의 데이터를 Q()객체 사용하여 카테고리에 맞게 전송

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인 페이지 카테고리 ( 판타지, 로맨스, 무협지)
- 카테고리 선택시 해당 카테고리에 저장된 데이터를 전송

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- Q()객체 사용법에 대한 이해도 증가
- 아쉬웠던 점으로는 readme 프로젝트에는 카테고리만으로 필터링을 구현하기로 기획되어있어서 
   가격순, 최신순, 베스트순 이렇게 세부적인 필터링을 적용해 보지 못한 점은 아쉽습니다.  
   프로젝트가 끝나면 혼자서 리팩토링 해볼 계획입니다.

<br />

## :: 기타 질문 및 특이 사항

2022-03-18 09:04 UTC, jamessoun93 requested changes

2022-03-18 09:04 UTC, jamessoun93 commented on products/views.py
> +            'rating_avg'    : book.review_set.all().aggregate(Avg('rating')),
지금 보시면 response의 이 부분이 아래와 같이 생겼는데요.
```python
"rating_avg": {
    "rating__avg": 5.0
},
```
여기서 rating__avg 값을 꺼내와 주시면 굳이 dictionary 하나가 추가로 필요하지 않게됩니다. 프론트에서 바로 rating_avg 의 값에 접근할 수 있다는 뜻이죠.
```python
result = [{
    ...,
    'avg_rating: book.review_set.all().aggregate(Avg('rating'))['rating__avg'],
    ...
}]
```

2022-03-18 09:04 UTC, jamessoun93 commented on products/views.py
> +        books = Product.objects.filter(q)
q 객체 사용 굳~ 근데 필터 가능 조건이 한개밖에 없나요?

2022-03-22 05:24 UTC, L-jungchan commented on products/views.py
> +            'rating_avg'    : book.review_set.all().aggregate(Avg('rating')),
수정완료했습니다!

2022-03-22 05:25 UTC, L-jungchan commented on products/views.py
> +        books = Product.objects.filter(q)
조건은 하나뿐이고 기획변경에 따라 view가 3개 추가됐습니다

2022-03-23 15:09 UTC, merged