[30기 김지성] Feat : reviews
wecode-bootcamp-korea/30-2nd-README-backend pull request #6
Opened 2022-03-18 09:31 UTC by jayce-kim1123

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 리뷰 기능 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰의 read, create, update, delete 기능 구현
2. 각 기능의 unit test 진행 (성공 4개, 에러 6개 포함 총 10개의 test case)

<img width="689" alt="스크린샷 2022-03-18 오후 6 16 21" src="https://user-images.githubusercontent.com/61664975/158976099-151bc897-9780-4993-9860-8af47b983bc9.png">

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- unit test 적용방법 

<br />

## :: 기타 질문 및 특이 사항
- ORM 최적화를 적용해보고 싶은데 최적화를 해야할 부분을 찾는 적절한 방법이 있는지 궁금합니다
    - npm loadtest 로 하나하나 검사해봐야 하는지
- unit test와 관련된 내용은 PR 문에서 어느 정도 선까지 적어야 하는지 궁금합니다

2022-03-19 19:13 UTC, jamessoun93 requested changes

2022-03-19 19:13 UTC, jamessoun93 commented on reviews/views.py
> +                review.save()
이 부분은 트랜잭션이 필요없습니다. 메모리에 로드된 review 객체의 프로퍼티 값을 두번 변경한 뒤 최종 UPDATE 쿼리는 한번만 날라가니까요.

2022-03-19 19:13 UTC, jamessoun93 commented on reviews/views.py
> +
exception 처리 추가해주세요!

2022-03-19 19:13 UTC, jamessoun93 commented on reviews/views.py
> +                return JsonResponse({'message':'REVIEW_EXISTED'}, status=400)
이미 작성한 리뷰가 존재할경우 400을 리턴해주는데 이 get_or_create()를 쓸 이유가 없습니다.

2022-03-19 19:13 UTC, jamessoun93 commented on reviews/views.py
> +                return JsonResponse({"message" : "NOT_EXIST_REVIEW"}, status=404)
로직이 조금 이해가 안되네요.
- POST 요청을 보면 유저 한명은 특정 제품에 대한 리뷰를 한번만 남길 수 있는 것 같은데, 여기서는 해당 제품 id에 대한 리뷰 여러개를 받을 수 있게 되어있네요?
- 그리고 review_id로 1,3,4가 들어왔는데 id 3을 가진 리뷰가 없어도 if문의 조건에 해당되지 않게됩니다.

2022-03-19 19:18 UTC, jayce-kim1123 commented on reviews/views.py
> +                review.save()
넵 수정하겠습니당

2022-03-19 19:30 UTC, jayce-kim1123 commented on reviews/views.py
> +
넵

2022-03-19 19:38 UTC, jayce-kim1123 commented on reviews/views.py
> +                return JsonResponse({"message" : "NOT_EXIST_REVIEW"}, status=404)
현재는 한 작품에 1개의 리뷰만 남길 수 있는 기획이지만 혹여 나중에 여러개의 리뷰를 남길 수 있는 방식으로 변경되는 상황이나 마이페이지가 생겨서 내가 남긴 리뷰를 모두 삭제할 수 있는 상황이 오지 않을까 생각해서 여러 개를 받을 수 있는 형태로 만들어봤던건데....

사실 저도 만들면서 이게 맞는걸까 싶었는데
말씀을 들어보니 제 3자로 하여금 혼란도 야기할 수 있고 현재 기획 목적에 크게 어긋난 부분인것 같네요
심지어 기능이 잘 작동하지도 않는 군요

여러 개를 받는 로직도 제대로 다시 짜본 후에
테스트 케이스도 좀 더 여러 방향으로 바꿔보고
그냥 1개의 id만 받아 수정하는 기획으로 바꿔서 수정하겠습니다!

2022-03-20 06:25 UTC, jayce-kim1123 commented on reviews/views.py
> +                return JsonResponse({'message':'REVIEW_EXISTED'}, status=400)
<img width="871" alt="스크린샷 2022-03-20 오후 2 52 30" src="https://user-images.githubusercontent.com/61664975/159150092-a9795323-9edf-45e2-b2e3-fdf89edfb039.png">

현재 저희 기획은 유저는 한 제품에 한 개의 리뷰만 남길 수 있는 기획입니다.

`
if Review.objects.filter(user_id=user.id, product_id=product_id).exists():
      return JsonResponse({'message':'REVIEW_ALREADY_EXISTED'}, status=400)
`

위와 같이 if문으로 존재하는 리뷰를 찾아내는 것으로 해당 기능을 구현할 수 있음을 알고 있었습니다
부끄럽게도 생각없이 get_or_create를 썼는데

말씀해주신 사항을 확인 후 ORM 최적화 세션에서 본 query_debugger를 사용하여 확인해봤고
get_or_create를 사용했을 떄는 생성 시와 에러 발생 시 각각 2회,
create 를 사용했을 때는 생성 시에는 2회 에러 발생 시 1회의 쿼리문을 실행하는 것을 확인했습니다

블로깅할게 하나 늘어났네요!
리뷰 감사합니다! 수정해서 올리겠습니다!

2022-03-21 12:54 UTC, merged